## 01/04/2026

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("c:\\Users\\mitta\\OneDrive\\Desktop\\DATASET\\data_set\\covid_toy - covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [4]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [5]:
df['gender'] = df['gender'].map({"Male" : 0 , 'Female' : 1})

In [6]:
df['has_covid'] = df['has_covid'].map({'Yes':1 , 'No':0})

In [7]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [8]:
df['cough'] = df['cough'].map( {"Mild" : 0 , 'Strong': 1 })

In [9]:
x = df.drop(columns=['has_covid'])

In [10]:
x = df.drop(columns=['city'])

In [11]:
y = df['has_covid']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state= 42)

In [14]:
np.round(x_train.describe(),2)

         age  gender   fever  cough  has_covid
count  80.00   80.00   80.00  80.00      80.00
mean   42.91    0.59  100.98   0.40       0.48
std    24.47    0.50    1.93   0.49       0.50
min     5.00    0.00   98.00   0.00       0.00
25%    20.00    0.00  100.00   0.00       0.00
50%    42.00    1.00  101.00   0.00       0.00
75%    65.00    1.00  102.00   1.00       1.00
max    84.00    1.00  104.00   1.00       1.00

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc = StandardScaler()

In [17]:
x_train_sc = sc.fit_transform(x_train)

In [18]:
# x_train_sc

In [19]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns )

In [20]:
type (x_train_sc)

numpy.ndarray

In [21]:
type (x_train_new)

pandas.DataFrame

In [22]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough  has_covid
count  80.00   80.00  80.00  80.00      80.00
mean   -0.00   -0.00  -0.00  -0.00       0.00
std     1.01    1.01   1.01   1.01       1.01
min    -1.56   -1.19  -1.56  -0.82      -0.95
25%    -0.94   -1.19  -0.51  -0.82      -0.95
50%    -0.04    0.84   0.01  -0.82      -0.95
75%     0.91    0.84   0.53   1.22       1.05
max     1.69    0.84   1.57   1.22       1.05