# 09 - 04 - 2026

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")
df.head()

<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
C:\Users\mitta\AppData\Local\Temp\ipykernel_1128\2352704592.py:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
df = df.dropna()

In [4]:
df = df.drop(columns = ['city' , 'age' ,'fever'])

In [5]:
df.head()

   gender cough has_covid
0    Male  Mild        No
1    Male  Mild       Yes
2    Male  Mild        No
3  Female  Mild        No
4  Female  Mild        No

In [6]:
df = df.dropna()

In [7]:
df.head()

   gender cough has_covid
0    Male  Mild        No
1    Male  Mild       Yes
2    Male  Mild        No
3  Female  Mild        No
4  Female  Mild        No

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories= [['Male' , 'Female'] , ['Mild' ,'Strong'] , ['No' , 'Yes']])

In [10]:
oe.ar = oe.fit_transform(df)

In [11]:
new_df = pd.DataFrame(oe.ar , columns = df.columns)

In [12]:
# ----------------------------------------------------------------------------------------------------------------

In [13]:
# second way

In [14]:
df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")
df.head()

<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
C:\Users\mitta\AppData\Local\Temp\ipykernel_1128\2352704592.py:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [15]:
df = df.dropna()

In [16]:
df = df.drop(columns = ['city' , 'age' ,'fever'])

In [17]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [19]:
oe = OrdinalEncoder(categories= [['Male' , 'Female'] , ['Mild' ,'Strong'] ])

In [20]:
oe_ar_in = oe.fit_transform(x)

In [21]:
y.head()

0     No
1    Yes
2     No
3     No
4     No
Name: has_covid, dtype: str

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
lb = LabelEncoder()

In [24]:
y = lb.fit_transform(y)

In [25]:
# ----------------------------------------------------

In [26]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_csv("C:\\Users\\mitta\\OneDrive\\Desktop\\ML\\Data Set\\tips - tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [28]:
df = df.dropna()

In [29]:
df.value_counts('day')

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [30]:
df = df.drop(columns = ['total_bill' , 'tip' ,'size' , 'day'])

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
df.value_counts("time")

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [33]:
oe = OrdinalEncoder(categories= [['Male' , 'Female'] , ['Yes','No'] , ['Dinner' , 'Lunch']])

In [34]:
oe.ar = oe.fit_transform(df)

In [35]:
new_df = pd.DataFrame(oe.ar , columns = df.columns)

In [36]:
new_df

     sex  smoker  time
0    1.0     1.0   0.0
1    0.0     1.0   0.0
2    0.0     1.0   0.0
3    0.0     1.0   0.0
4    1.0     1.0   0.0
..   ...     ...   ...
239  0.0     1.0   0.0
240  1.0     0.0   0.0
241  0.0     0.0   0.0
242  0.0     1.0   0.0
243  1.0     1.0   0.0

[244 rows x 3 columns]